site_name: xenondevs docs
site_url: https://xenondevs.tree.pink/
repo_url: https://github.com/xenondevs/Nova
repo_name: xenondevs/Nova
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 xenondevs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xenondevs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/hnEknVWvUe
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/xenondevs
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
  features:
    - content.tabs.link
    - navigation.tabs
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          site_name: xenondevs docs
        zh:
          name: 简体中文
          site_name: xenondevs 帮助文档
      nav_translations:
        zh:
          "Home": 首页
          "For Server Admins": 安装及配置帮助
          "Setup": 安装
          "Configuration": 插件配置
          "Compatibility": 兼容性
          "List of compatible Plugins": 兼容的插件
          "Troubleshooting": 故障排除
          "Recipes": 配方
          "Custom Recipes": 自定义配方
          "Vanilla Recipe Types": 原版类配方
          "Machines Recipe Types": 机械类配方
          "FAQ": 常见问题
          "Addons": 扩展
          "Getting Started": 入门
          "AssetPacks": 资源包
          "Basics": 基础
          "Creating Items": 创建物品
          "Creating Blocks": 创建方块
          "Creating GUIs": "创建 GUI"
          "Language Files": 语言文件
          "Items": 物品相关
          "Registering Materials": 创建材料
          "Item Behaviors": 物品行为
          "Using ItemNovaMaterial": "使用 ItemNovaMaterial"
          "Item Categories": 物品种类
          "TileEntities": 方块实体
          "Config": 配置
          "TileEntity Data": 方块实体信息
          "Upgrades": 升级
          "Particles": 粒子效果
          "GUI Textures": "GUI 贴图"
          "Advancements": 进度
          "Recipes": 配方
          "Structure": 结构

extra_css:
  - assets/stylesheets/extra.css

nav:
  - "Nova":
      - "Home": "nova/index.md"
      - "For Server Admins":
          - "Setup": "nova/admin/setup.md"
          - "Configuration": "nova/admin/configuration.md"
          - "Compatibility":
              - "List of compatible Plugins": "nova/admin/compatibility/index.md"
              - "Troubleshooting": "nova/admin/compatibility/troubleshooting.md"
              - "ItemsAdder": "nova/admin/compatibility/itemsadder.md"
              - "GriefDefender": "nova/admin/compatibility/griefdefender.md"
          - "Recipes":
              - "Custom Recipes": "nova/admin/recipes/index.md"
              - "Vanilla Recipe Types": "nova/admin/recipes/vanilla.md"
              - "Machines Recipe Types": "nova/admin/recipes/machines.md"
          - "FAQ": "nova/admin/faq.md"
      - "Addons":
          - "Getting Started": "nova/addon/getting-started.md"
          - "addon.yml": "nova/addon/addon.yml.md"
          - "AssetPacks":
              - "Basics": "nova/addon/asset-packs/assetpack-basics.md"
              - "Creating Items": "nova/addon/asset-packs/creating-items.md"
              - "Creating Blocks": "nova/addon/asset-packs/creating-blocks.md"
              - "Creating GUIs": "nova/addon/asset-packs/creating-guis.md"
              - "Language Files": "nova/addon/asset-packs/language-files.md"
          - "Items":
              - "Registering Materials": "nova/addon/items/registering-materials.md"
              - "Item Behaviors": "nova/addon/items/item-behaviors.md"
              - "Using ItemNovaMaterial": "nova/addon/items/using-item-nova-material.md"
              - "Item Categories": "nova/addon/items/item-categories.md"
          - "Configs": "nova/addon/configs.md"
          - "Blocks":
              - "Registering Materials": "nova/addon/blocks/registering-materials.md"
              - "TileEntities":
                  - "Basics": "nova/addon/blocks/tileentity/base.md"
                  - "Config": "nova/addon/blocks/tileentity/config.md"
                  - "GUI": "nova/addon/blocks/tileentity/gui.md"
                  - "TileEntity Data": "nova/addon/blocks/tileentity/data.md"
                  - "Holders": "nova/addon/blocks/tileentity/holders.md"
                  - "Upgrades": "nova/addon/blocks/tileentity/upgrades.md"
                  - "Particles": "nova/addon/blocks/tileentity/particles.md"
          - "GUI Textures": "nova/addon/guitexture.md"
          - "Actionbar Overlays": "nova/addon/actionbaroverlay.md"
          - "Advancements": "nova/addon/advancements.md"
          - "Attachments": "nova/addon/attachments.md"
          - "Abilities": "nova/addon/abilities.md"
          - "Recipes": "nova/addon/recipes.md"
      - "API for Plugins":
          - "Getting Started": "nova/api/index.md"
          - "Protection": "nova/api/protection/protectionintegration.md"
          - "NovaMaterial": "nova/api/material/index.md"
          - "Blocks":
              - "BlockManager": "nova/api/blocks/blockmanager.md"
              - "BlockState": "nova/api/blocks/blockstate.md"
          - "TileEntity":
              - "TileEntityManager": "nova/api/tileentity/tileentitymanager.md"
              - "TileEntity": "nova/api/tileentity/tileentity.md"
          - "Events":
              - "NovaLoadDataEvent": "nova/api/events/novaloaddataevent.md"
              - "TileEntityBreakBlockEvent": "nova/api/events/tileentitybreakblockevent.md"
  - "InvUI":
      - "Getting Started": "invui/index.md"
      - "Basics": "invui/basics.md"
      - "Items": "invui/items.md"
      - "Structure": "invui/structure.md"
      - "GUIs":
          - "Overview": "invui/guis/index.md"
          - "Normal GUI": "invui/guis/normal.md"
          - "Paged GUI": "invui/guis/paged.md"
          - "Scroll GUI": "invui/guis/scroll.md"
          - "Tab GUI": "invui/guis/tab.md"
      - "Windows": "invui/windows.md"
      - "VirtualInventory": "invui/virtualinventory.md"
  - "CBF":
      - "Getting Started": "cbf/index.md"
      - "Binary Adapters": "cbf/binaryadapter.md"
      - "Instance Creators": "cbf/instancecreator.md"
      - "Serialization": "cbf/serialization.md"
      - "Compounds": "cbf/compound.md"
