repo_url: https://github.com/xenondevs/Nova
repo_name: xenondevs/Nova
copyright: Copyright &copy; 2023 xenondevs. Chinese translation provided by NetheriteTree.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xenondevs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/EpVMXtXB2t
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/xenondevs
    - icon: fontawesome/solid/pen
      link: https://github.com/NetheriteTree/xenondevsDocs
      name: 完善中文翻译
  analytics:
    provider: google
    property: G-D07WH8Y481
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

theme:
  name: material
  font: false
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: deep purple
    accent: green
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: false
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - assets/stylesheets/extra.css

extra_css:
  - assets/stylesheets/extra.css