name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/sites
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: |
          mkdocs build -f ../nova.yml
          mkdocs build -f ../invui.yml
          mkdocs build -f ../cbf.yml
          mv nova/CNAME CNAME
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git add .
          git commit -m "docs"
          git push --set-upstream origin gh-pages --force
