name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-minify-plugin
      - run: |
          mkdocs build -f docs/nova.yml
          mkdocs build -f docs/invui.yml
          mkdocs build -f docs/cbf.yml
      - name: push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/sites
          SQUASH_HISTORY: true
          MESSAGE: "docs"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
