name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'docs/sites'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: mkdocs build -f docs/nova.yml
      - run: mkdocs build -f docs/invui.yml
      - run: mkdocs build -f docs/cbf.yml
      - run: mv docs/sites/nova/CNAME docs/sites/CNAME
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git add .
          git commit -m "docs"
          git push --set-upstream origin gh-pages --force
