name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: mkdocs gh-deploy -f docs/nova.yml --force --no-history --site-dir nova
      - run: mkdocs gh-deploy -f docs/invui.yml --site-dir invui
      - run: mkdocs gh-deploy -f docs/cbf.yml --site-dir cbf
