name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: mkdocs build -f docs/cbf.yml
      - run: mkdocs build -f docs/invui.yml
      - run: mkdocs build -f docs/nova.yml
      - name: copy
        env:
          SRC_FOLDER_PATH: 'docs/sites'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout --orphan $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD || git commit -am "deploy files"
          git push origin $TARGET_BRANCH --force
